import {
  Zap,
  TrendingUp,
  TrendingDown,
  AlertTriangle,
  CheckCircle,
} from 'lucide-react';
import PageHeader from '../components/shared/PageHeader';
import Card from '../components/shared/Card';
import { useOverviewKpis, useOverviewNarrative } from '../api/hooks';
import type { KpiData } from '../types';

function KpiCard({ kpi, index }: { kpi: KpiData; index: number }) {
  return (
    <Card hover className={`animate-fade-in-up stagger-${index + 1}`}>
      <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">
        {kpi.label}
      </p>
      <p className="mt-3 text-3xl font-bold tracking-tight text-slate-900">
        {kpi.value}
      </p>
      <p className="mt-1.5 flex items-center gap-1 text-xs text-slate-500">
        {kpi.trend > 0 && (
          <TrendingUp className="h-3 w-3 text-emerald-500" />
        )}
        {kpi.trend < 0 && (
          <TrendingDown className="h-3 w-3 text-red-500" />
        )}
        {kpi.trend !== 0 && (
          <span
            className={
              kpi.trend > 0 ? 'text-emerald-600' : 'text-red-600'
            }
          >
            {kpi.trend > 0 ? '+' : ''}
            {kpi.trend}
          </span>
        )}
        <span>{kpi.trend_label}</span>
      </p>
    </Card>
  );
}

function KpiSkeleton({ index }: { index: number }) {
  return (
    <Card className={`animate-fade-in-up stagger-${index + 1}`}>
      <div className="h-3 w-24 rounded bg-slate-200 animate-pulse" />
      <div className="mt-4 h-8 w-16 rounded bg-slate-200 animate-pulse" />
      <div className="mt-2 h-3 w-20 rounded bg-slate-100 animate-pulse" />
    </Card>
  );
}

export default function Overview() {
  const { data: kpis, isLoading, isError } = useOverviewKpis();
  const { data: narrative, isLoading: narrativeLoading } =
    useOverviewNarrative();

  const kpiList: KpiData[] = kpis
    ? [
        kpis.total_customers,
        kpis.monthly_revenue,
        kpis.churn_rate,
        kpis.avg_sentiment,
        kpis.active_anomalies,
      ]
    : [];

  return (
    <div>
      <PageHeader
        title="Executive Overview"
        description="AI-powered pulse check on customer health, revenue, and risk"
      />

      {/* KPI Cards */}
      <div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-5">
        {isLoading
          ? Array.from({ length: 5 }).map((_, i) => (
              <KpiSkeleton key={i} index={i} />
            ))
          : isError
            ? Array.from({ length: 5 }).map((_, i) => (
                <Card
                  key={i}
                  className={`animate-fade-in-up stagger-${i + 1}`}
                >
                  <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">
                    --
                  </p>
                  <p className="mt-3 text-sm text-red-500">
                    Failed to load
                  </p>
                </Card>
              ))
            : kpiList.map((kpi, i) => (
                <KpiCard key={kpi.label} kpi={kpi} index={i} />
              ))}
      </div>

      {/* AI Narrative */}
      <Card className="mt-6 animate-fade-in-up stagger-5 border-emerald-100 bg-emerald-50/40">
        <div className="mb-3 flex items-center gap-2">
          <span className="flex items-center gap-1.5 rounded-full bg-emerald-100 px-2.5 py-1 text-[11px] font-semibold text-emerald-700">
            <Zap className="h-3 w-3" />
            Generated by AI
          </span>
        </div>

        {narrativeLoading ? (
          <div className="space-y-2">
            <div className="h-4 w-3/4 rounded bg-emerald-100 animate-pulse" />
            <div className="h-4 w-1/2 rounded bg-emerald-100 animate-pulse" />
          </div>
        ) : narrative ? (
          <div className="space-y-3">
            <p className="text-sm leading-relaxed text-slate-700">
              {narrative.executive_summary}
            </p>

            {narrative.highlights.length > 0 && (
              <div className="space-y-1">
                {narrative.highlights.map((h) => (
                  <p
                    key={h}
                    className="flex items-start gap-1.5 text-xs text-emerald-700"
                  >
                    <CheckCircle className="mt-0.5 h-3 w-3 shrink-0" />
                    {h}
                  </p>
                ))}
              </div>
            )}

            {narrative.concerns.length > 0 && (
              <div className="space-y-1">
                {narrative.concerns.map((c) => (
                  <p
                    key={c}
                    className="flex items-start gap-1.5 text-xs text-amber-700"
                  >
                    <AlertTriangle className="mt-0.5 h-3 w-3 shrink-0" />
                    {c}
                  </p>
                ))}
              </div>
            )}

            <p className="text-[10px] text-slate-400">
              Generated {new Date(narrative.generated_at).toLocaleString()}
            </p>
          </div>
        ) : (
          <p className="text-sm leading-relaxed text-slate-600">
            Executive narrative will appear here once the analysis pipeline
            has been run.
          </p>
        )}
      </Card>
    </div>
  );
}
