import {
  Zap,
  AlertTriangle,
  CheckCircle,
  BarChart3,
  ShieldCheck,
} from 'lucide-react';
import PageHeader from '../components/shared/PageHeader';
import Card from '../components/shared/Card';
import StatCard from '../components/shared/StatCard';
import EmptyState from '../components/shared/EmptyState';
import { useOverviewKpis, useOverviewNarrative, useAgentsSummary } from '../api/hooks';
import type { KpiData } from '../types';

function generateSparklineData(trend: number): number[] {
  const base = 100;
  const target = base * (1 + trend / 100);
  return Array.from({ length: 7 }, (_, i) =>
    base + ((target - base) * i) / 6 + (Math.sin(i * 1.5) * 3)
  );
}

function HeroSkeleton() {
  return (
    <Card variant="hero" className="animate-fade-in-up">
      <div className="h-3 w-32 rounded-md shimmer" />
      <div className="mt-4 h-10 w-24 rounded-md shimmer" />
      <div className="mt-2 h-3 w-20 rounded-md shimmer" />
      <div className="mt-3 h-[50px] w-[72px] rounded-md shimmer" />
    </Card>
  );
}

function SecondaryKpiSkeleton() {
  return (
    <Card variant="elevated" className="animate-fade-in-up">
      <div className="h-3 w-24 rounded-md shimmer" />
      <div className="mt-4 h-8 w-16 rounded-md shimmer" />
      <div className="mt-2 h-3 w-20 rounded-md shimmer" />
    </Card>
  );
}

export default function Overview() {
  const { data: kpis, isLoading, isError } = useOverviewKpis();
  const { data: narrative, isLoading: narrativeLoading } =
    useOverviewNarrative();
  const { data: agentData } = useAgentsSummary();

  const kpiList: KpiData[] = kpis
    ? [
        kpis.total_customers,
        kpis.monthly_revenue,
        kpis.churn_rate,
        kpis.avg_sentiment,
        kpis.active_anomalies,
      ]
    : [];

  // Split into hero (first 2) and secondary (remaining 3)
  const heroKpis = kpiList.slice(0, 2);
  const secondaryKpis = kpiList.slice(2);

  // Pipeline health from agent runs
  const latestRuns = agentData?.runs ?? [];

  return (
    <div>
      <PageHeader
        title="Executive Overview"
        description="AI-powered pulse check on customer health, revenue, and risk"
      />

      {isLoading ? (
        <>
          {/* Hero skeleton */}
          <div className="grid grid-cols-1 gap-5 sm:grid-cols-2">
            <HeroSkeleton />
            <HeroSkeleton />
          </div>
          {/* Secondary skeleton */}
          <div className="mt-5 grid grid-cols-1 gap-5 sm:grid-cols-3">
            <SecondaryKpiSkeleton />
            <SecondaryKpiSkeleton />
            <SecondaryKpiSkeleton />
          </div>
        </>
      ) : isError ? (
        <Card className="border-[rgba(248,113,113,0.2)] bg-[rgba(248,113,113,0.1)]">
          <p className="flex items-center gap-2 text-sm text-[rgba(248,113,113,0.9)]">
            <AlertTriangle className="h-4 w-4" />
            Failed to load overview data.
          </p>
        </Card>
      ) : kpiList.length === 0 ? (
        <EmptyState
          icon={BarChart3}
          title="No metrics available"
          description="Executive KPIs will appear here once the intelligence pipeline has processed this workspace's data."
        />
      ) : (
        <>
          {/* Hero KPI Row — 2 large cards */}
          <div className="grid grid-cols-1 gap-5 sm:grid-cols-2">
            {heroKpis.map((kpi, i) => (
              <StatCard
                key={kpi.label}
                title={kpi.label}
                value={kpi.value}
                variant="hero"
                trend={{ value: kpi.trend, label: kpi.trend_label }}
                sparkline={{ data: generateSparklineData(kpi.trend) }}
                className={`animate-fade-in-up stagger-${i + 1}`}
              />
            ))}
          </div>

          {/* Secondary KPI Row — 3 smaller cards */}
          <div className="mt-5 grid grid-cols-1 gap-5 sm:grid-cols-3">
            {secondaryKpis.map((kpi, i) => (
              <StatCard
                key={kpi.label}
                title={kpi.label}
                value={kpi.value}
                trend={{ value: kpi.trend, label: kpi.trend_label }}
                className={`animate-fade-in-up stagger-${i + 3}`}
              />
            ))}
          </div>
        </>
      )}

      {/* Bottom Section — 60/40 split: Narrative + Pipeline Health */}
      <div className="mt-6 grid grid-cols-1 gap-6 xl:grid-cols-5">
        {/* AI Narrative — 60% */}
        <Card variant="hero" className="animate-fade-in-up stagger-5 xl:col-span-3">
          <div className="mb-3 flex items-center gap-2">
            <span className="flex items-center gap-1.5 rounded-full bg-[rgba(129,140,248,0.15)] px-2.5 py-1 text-[11px] font-semibold text-[var(--color-primary-400)]">
              <Zap className="h-3 w-3" />
              Generated by AI
            </span>
          </div>

          {narrativeLoading ? (
            <div className="space-y-2">
              <div className="h-4 w-3/4 rounded-md shimmer" />
              <div className="h-4 w-1/2 rounded-md shimmer" />
            </div>
          ) : narrative ? (
            <div className="space-y-3">
              <p className="text-sm leading-relaxed text-[rgba(255,255,255,0.7)]">
                {narrative.executive_summary}
              </p>

              {narrative.highlights.length > 0 && (
                <div className="space-y-1">
                  {narrative.highlights.map((h) => (
                    <p
                      key={h}
                      className="flex items-start gap-1.5 text-xs text-[rgba(255,255,255,0.7)]"
                    >
                      <CheckCircle className="mt-0.5 h-3 w-3 shrink-0 text-[var(--color-success)]" />
                      {h}
                    </p>
                  ))}
                </div>
              )}

              {narrative.concerns.length > 0 && (
                <div className="space-y-1">
                  {narrative.concerns.map((c) => (
                    <p
                      key={c}
                      className="flex items-start gap-1.5 text-xs text-[rgba(255,255,255,0.7)]"
                    >
                      <AlertTriangle className="mt-0.5 h-3 w-3 shrink-0 text-[var(--color-warning)]" />
                      {c}
                    </p>
                  ))}
                </div>
              )}

              <p className="text-[10px] text-[rgba(255,255,255,0.35)]">
                Generated {new Date(narrative.generated_at).toLocaleString()}
              </p>
            </div>
          ) : (
            <p className="text-sm leading-relaxed text-[rgba(255,255,255,0.55)]">
              The AI-generated executive narrative will appear here once the
              intelligence pipeline has processed this workspace.
            </p>
          )}
        </Card>

        {/* Pipeline Health — 40% */}
        <Card className="animate-fade-in-up stagger-6 xl:col-span-2">
          <div className="panel-title-bar">
            <ShieldCheck className="h-4 w-4 text-[var(--color-success)]" />
            <h3 className="text-sm font-semibold">
              Pipeline Health
            </h3>
          </div>

          {latestRuns.length > 0 ? (
            <div className="space-y-2">
              {latestRuns.map((run) => (
                <div
                  key={run.id}
                  className="flex items-center justify-between gap-4 rounded-lg bg-[rgba(255,255,255,0.04)] px-3 py-2.5"
                >
                  <div className="flex min-w-0 items-center gap-2.5">
                    {run.status === 'completed' ? (
                      <CheckCircle className="h-3.5 w-3.5 text-[var(--color-success)]" />
                    ) : run.status === 'failed' ? (
                      <AlertTriangle className="h-3.5 w-3.5 text-[var(--color-danger)]" />
                    ) : (
                      <div className="h-3.5 w-3.5 animate-spin rounded-full border-2 border-[rgba(255,255,255,0.1)] border-t-[var(--color-primary-400)]" />
                    )}
                    <span className="truncate text-xs font-medium text-[rgba(255,255,255,0.78)]">
                      {run.agent_name}
                    </span>
                  </div>
                  {run.duration_ms != null && (
                    <span className="shrink-0 rounded-md bg-[rgba(255,255,255,0.05)] px-2 py-0.5 font-mono text-[11px] text-[rgba(255,255,255,0.58)]">
                      {(run.duration_ms / 1000).toFixed(1)}s
                    </span>
                  )}
                </div>
              ))}
            </div>
          ) : (
            <p className="text-xs text-[rgba(255,255,255,0.4)]">
              Pipeline status will appear after generation completes.
            </p>
          )}
        </Card>
      </div>
    </div>
  );
}
