import PageHeader from '../components/shared/PageHeader';

export default function Overview() {
  return (
    <div>
      <PageHeader
        title="Executive Overview"
        description="AI-powered pulse check on customer health, revenue, and risk"
      />
      <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-5">
        {['Total Customers', 'Monthly Revenue', 'Churn Rate', 'Avg Sentiment', 'Anomalies'].map(
          (label) => (
            <div
              key={label}
              className="rounded-lg border border-gray-200 bg-white p-6 shadow-sm"
            >
              <p className="text-sm font-medium text-gray-500">{label}</p>
              <p className="mt-2 text-3xl font-semibold text-gray-900">—</p>
            </div>
          )
        )}
      </div>
      <div className="mt-6 rounded-lg border border-blue-100 bg-blue-50 p-6">
        <div className="flex items-center gap-2 mb-2">
          <span className="text-xs font-medium text-blue-600 bg-blue-100 px-2 py-0.5 rounded">
            Generated by AI
          </span>
        </div>
        <p className="text-sm text-gray-700">
          Executive narrative will appear here once the analysis pipeline has been run.
        </p>
      </div>
    </div>
  );
}
